/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LitReviewReference {
  'id' : string,
  'title' : string,
  'doiOrUrl' : string,
  'journal' : string,
  'year' : string,
  'authors' : Array<string>,
  'notes' : string,
}
export interface LiteratureReview {
  'references' : Array<LitReviewReference>,
  'researchGap' : string,
  'createdAt' : Time,
  'methodologies' : Array<string>,
  'updatedAt' : Time,
  'sessionId' : string,
}
export interface Objective {
  'id' : ObjectiveId,
  'text' : string,
  'targetPaperCount' : bigint,
  'sessionId' : SessionId,
  'discoveredPapers' : Array<PaperId>,
}
export type ObjectiveId = string;
export interface Paper {
  'id' : PaperId,
  'abstractText' : string,
  'title' : string,
  'references' : Array<string>,
  'fetchedContent' : [] | [string],
  'sourceUrl' : string,
  'relevanceScore' : [] | [number],
  'sourceType' : string,
  'keywords' : Array<string>,
  'summary' : [] | [string],
  'addedAt' : Time,
  'authors' : Array<string>,
  'fullTextAvailable' : boolean,
  'citationAPA' : [] | [string],
  'citationMLA' : [] | [string],
}
export type PaperId = string;
export interface ResearchSession {
  'id' : SessionId,
  'status' : string,
  'title' : string,
  'createdAt' : Time,
  'proposalText' : string,
  'objectives' : Array<ObjectiveId>,
  'proposalFileName' : [] | [string],
}
export interface SearchResponse {
  'arxivResults' : Array<Paper>,
  'semanticScholarResults' : Array<Paper>,
}
export type SessionId = string;
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : Principal,
  'displayName' : string,
  'institution' : [] | [string],
  'createdAt' : Time,
  'researchField' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPaper' : ActorMethod<
    [PaperId, string, Array<string>, string, string, string],
    Paper
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createObjective' : ActorMethod<
    [ObjectiveId, SessionId, string, bigint],
    Objective
  >,
  'createSession' : ActorMethod<
    [SessionId, string, string, [] | [string]],
    ResearchSession
  >,
  'createUserProfile' : ActorMethod<
    [string, [] | [string], [] | [string]],
    UserProfile
  >,
  'deleteLiteratureReview' : ActorMethod<[string], undefined>,
  'deleteObjective' : ActorMethod<[ObjectiveId], undefined>,
  'deletePaper' : ActorMethod<[PaperId], undefined>,
  'deleteSession' : ActorMethod<[string], undefined>,
  'getAllSessions' : ActorMethod<[], Array<ResearchSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLiteratureReview' : ActorMethod<[string], [] | [LiteratureReview]>,
  'getObjective' : ActorMethod<[ObjectiveId], Objective>,
  'getObjectivesBySession' : ActorMethod<[SessionId], Array<Objective>>,
  'getPaper' : ActorMethod<[PaperId], Paper>,
  'getPapersByObjective' : ActorMethod<[ObjectiveId], Array<Paper>>,
  'getPapersBySession' : ActorMethod<[SessionId], Array<Paper>>,
  'getSession' : ActorMethod<[string], ResearchSession>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLiteratureReview' : ActorMethod<
    [string, string, Array<string>, Array<LitReviewReference>],
    LiteratureReview
  >,
  'searchExternalDatabases' : ActorMethod<[string], SearchResponse>,
  'searchSessionsByTitle' : ActorMethod<[string], Array<ResearchSession>>,
  'transformOutcall' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePaper' : ActorMethod<[Paper], Paper>,
  'updateSessionTitle' : ActorMethod<[string, string], ResearchSession>,
  'updateUserProfile' : ActorMethod<
    [string, [] | [string], [] | [string]],
    UserProfile
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];