/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PaperId = IDL.Text;
export const Time = IDL.Int;
export const Paper = IDL.Record({
  'id' : PaperId,
  'abstractText' : IDL.Text,
  'title' : IDL.Text,
  'references' : IDL.Vec(IDL.Text),
  'fetchedContent' : IDL.Opt(IDL.Text),
  'sourceUrl' : IDL.Text,
  'relevanceScore' : IDL.Opt(IDL.Float64),
  'sourceType' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
  'summary' : IDL.Opt(IDL.Text),
  'addedAt' : Time,
  'authors' : IDL.Vec(IDL.Text),
  'fullTextAvailable' : IDL.Bool,
  'citationAPA' : IDL.Opt(IDL.Text),
  'citationMLA' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ObjectiveId = IDL.Text;
export const SessionId = IDL.Text;
export const Objective = IDL.Record({
  'id' : ObjectiveId,
  'text' : IDL.Text,
  'targetPaperCount' : IDL.Nat,
  'sessionId' : SessionId,
  'discoveredPapers' : IDL.Vec(PaperId),
});
export const ResearchSession = IDL.Record({
  'id' : SessionId,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'proposalText' : IDL.Text,
  'objectives' : IDL.Vec(ObjectiveId),
  'proposalFileName' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'institution' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'researchField' : IDL.Opt(IDL.Text),
});
export const LitReviewReference = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'doiOrUrl' : IDL.Text,
  'journal' : IDL.Text,
  'year' : IDL.Text,
  'authors' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
});
export const LiteratureReview = IDL.Record({
  'references' : IDL.Vec(LitReviewReference),
  'researchGap' : IDL.Text,
  'createdAt' : Time,
  'methodologies' : IDL.Vec(IDL.Text),
  'updatedAt' : Time,
  'sessionId' : IDL.Text,
});
export const SearchResponse = IDL.Record({
  'arxivResults' : IDL.Vec(Paper),
  'semanticScholarResults' : IDL.Vec(Paper),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPaper' : IDL.Func(
      [PaperId, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
      [Paper],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createObjective' : IDL.Func(
      [ObjectiveId, SessionId, IDL.Text, IDL.Nat],
      [Objective],
      [],
    ),
  'createSession' : IDL.Func(
      [SessionId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [ResearchSession],
      [],
    ),
  'createUserProfile' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [UserProfile],
      [],
    ),
  'deleteLiteratureReview' : IDL.Func([IDL.Text], [], []),
  'deleteObjective' : IDL.Func([ObjectiveId], [], []),
  'deletePaper' : IDL.Func([PaperId], [], []),
  'deleteSession' : IDL.Func([IDL.Text], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(ResearchSession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLiteratureReview' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LiteratureReview)],
      ['query'],
    ),
  'getObjective' : IDL.Func([ObjectiveId], [Objective], ['query']),
  'getObjectivesBySession' : IDL.Func(
      [SessionId],
      [IDL.Vec(Objective)],
      ['query'],
    ),
  'getPaper' : IDL.Func([PaperId], [Paper], ['query']),
  'getPapersByObjective' : IDL.Func([ObjectiveId], [IDL.Vec(Paper)], ['query']),
  'getPapersBySession' : IDL.Func([SessionId], [IDL.Vec(Paper)], ['query']),
  'getSession' : IDL.Func([IDL.Text], [ResearchSession], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLiteratureReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(LitReviewReference)],
      [LiteratureReview],
      [],
    ),
  'searchExternalDatabases' : IDL.Func([IDL.Text], [SearchResponse], []),
  'searchSessionsByTitle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ResearchSession)],
      ['query'],
    ),
  'transformOutcall' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePaper' : IDL.Func([Paper], [Paper], []),
  'updateSessionTitle' : IDL.Func([IDL.Text, IDL.Text], [ResearchSession], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [UserProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PaperId = IDL.Text;
  const Time = IDL.Int;
  const Paper = IDL.Record({
    'id' : PaperId,
    'abstractText' : IDL.Text,
    'title' : IDL.Text,
    'references' : IDL.Vec(IDL.Text),
    'fetchedContent' : IDL.Opt(IDL.Text),
    'sourceUrl' : IDL.Text,
    'relevanceScore' : IDL.Opt(IDL.Float64),
    'sourceType' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
    'summary' : IDL.Opt(IDL.Text),
    'addedAt' : Time,
    'authors' : IDL.Vec(IDL.Text),
    'fullTextAvailable' : IDL.Bool,
    'citationAPA' : IDL.Opt(IDL.Text),
    'citationMLA' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ObjectiveId = IDL.Text;
  const SessionId = IDL.Text;
  const Objective = IDL.Record({
    'id' : ObjectiveId,
    'text' : IDL.Text,
    'targetPaperCount' : IDL.Nat,
    'sessionId' : SessionId,
    'discoveredPapers' : IDL.Vec(PaperId),
  });
  const ResearchSession = IDL.Record({
    'id' : SessionId,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'proposalText' : IDL.Text,
    'objectives' : IDL.Vec(ObjectiveId),
    'proposalFileName' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'institution' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'researchField' : IDL.Opt(IDL.Text),
  });
  const LitReviewReference = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'doiOrUrl' : IDL.Text,
    'journal' : IDL.Text,
    'year' : IDL.Text,
    'authors' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
  });
  const LiteratureReview = IDL.Record({
    'references' : IDL.Vec(LitReviewReference),
    'researchGap' : IDL.Text,
    'createdAt' : Time,
    'methodologies' : IDL.Vec(IDL.Text),
    'updatedAt' : Time,
    'sessionId' : IDL.Text,
  });
  const SearchResponse = IDL.Record({
    'arxivResults' : IDL.Vec(Paper),
    'semanticScholarResults' : IDL.Vec(Paper),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPaper' : IDL.Func(
        [PaperId, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Text],
        [Paper],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createObjective' : IDL.Func(
        [ObjectiveId, SessionId, IDL.Text, IDL.Nat],
        [Objective],
        [],
      ),
    'createSession' : IDL.Func(
        [SessionId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [ResearchSession],
        [],
      ),
    'createUserProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [UserProfile],
        [],
      ),
    'deleteLiteratureReview' : IDL.Func([IDL.Text], [], []),
    'deleteObjective' : IDL.Func([ObjectiveId], [], []),
    'deletePaper' : IDL.Func([PaperId], [], []),
    'deleteSession' : IDL.Func([IDL.Text], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(ResearchSession)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLiteratureReview' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LiteratureReview)],
        ['query'],
      ),
    'getObjective' : IDL.Func([ObjectiveId], [Objective], ['query']),
    'getObjectivesBySession' : IDL.Func(
        [SessionId],
        [IDL.Vec(Objective)],
        ['query'],
      ),
    'getPaper' : IDL.Func([PaperId], [Paper], ['query']),
    'getPapersByObjective' : IDL.Func(
        [ObjectiveId],
        [IDL.Vec(Paper)],
        ['query'],
      ),
    'getPapersBySession' : IDL.Func([SessionId], [IDL.Vec(Paper)], ['query']),
    'getSession' : IDL.Func([IDL.Text], [ResearchSession], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLiteratureReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(LitReviewReference)],
        [LiteratureReview],
        [],
      ),
    'searchExternalDatabases' : IDL.Func([IDL.Text], [SearchResponse], []),
    'searchSessionsByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ResearchSession)],
        ['query'],
      ),
    'transformOutcall' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePaper' : IDL.Func([Paper], [Paper], []),
    'updateSessionTitle' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ResearchSession],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [UserProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };