/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LiteratureReview {
    references: Array<LitReviewReference>;
    researchGap: string;
    createdAt: Time;
    methodologies: Array<string>;
    updatedAt: Time;
    sessionId: string;
}
export type PaperId = string;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type SessionId = string;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SearchResponse {
    arxivResults: Array<Paper>;
    semanticScholarResults: Array<Paper>;
}
export type ObjectiveId = string;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ResearchSession {
    id: SessionId;
    status: string;
    title: string;
    createdAt: Time;
    proposalText: string;
    objectives: Array<ObjectiveId>;
    proposalFileName?: string;
}
export interface Paper {
    id: PaperId;
    abstractText: string;
    title: string;
    references: Array<string>;
    fetchedContent?: string;
    sourceUrl: string;
    relevanceScore?: number;
    sourceType: string;
    keywords: Array<string>;
    summary?: string;
    addedAt: Time;
    authors: Array<string>;
    fullTextAvailable: boolean;
    citationAPA?: string;
    citationMLA?: string;
}
export interface LitReviewReference {
    id: string;
    title: string;
    doiOrUrl: string;
    journal: string;
    year: string;
    authors: Array<string>;
    notes: string;
}
export interface Objective {
    id: ObjectiveId;
    text: string;
    targetPaperCount: bigint;
    sessionId: SessionId;
    discoveredPapers: Array<PaperId>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    principal: Principal;
    displayName: string;
    institution?: string;
    createdAt: Time;
    researchField?: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPaper(id: PaperId, title: string, authors: Array<string>, sourceType: string, sourceUrl: string, abstractText: string): Promise<Paper>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createObjective(id: ObjectiveId, sessionId: SessionId, text: string, targetPaperCount: bigint): Promise<Objective>;
    createSession(id: SessionId, title: string, proposalText: string, proposalFileName: string | null): Promise<ResearchSession>;
    createUserProfile(displayName: string, institution: string | null, researchField: string | null): Promise<UserProfile>;
    deleteLiteratureReview(sessionId: string): Promise<void>;
    deleteObjective(_id: ObjectiveId): Promise<void>;
    deletePaper(_id: PaperId): Promise<void>;
    deleteSession(_id: string): Promise<void>;
    getAllSessions(): Promise<Array<ResearchSession>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLiteratureReview(sessionId: string): Promise<LiteratureReview | null>;
    getObjective(_id: ObjectiveId): Promise<Objective>;
    getObjectivesBySession(sessionId: SessionId): Promise<Array<Objective>>;
    getPaper(_id: PaperId): Promise<Paper>;
    getPapersByObjective(_objectiveId: ObjectiveId): Promise<Array<Paper>>;
    getPapersBySession(_sessionId: SessionId): Promise<Array<Paper>>;
    getSession(_id: string): Promise<ResearchSession>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveLiteratureReview(sessionId: string, researchGap: string, methodologies: Array<string>, refs: Array<LitReviewReference>): Promise<LiteratureReview>;
    searchExternalDatabases(_objective: string): Promise<SearchResponse>;
    searchSessionsByTitle(_searchText: string): Promise<Array<ResearchSession>>;
    transformOutcall(input: TransformationInput): Promise<TransformationOutput>;
    updatePaper(paper: Paper): Promise<Paper>;
    updateSessionTitle(id: string, newTitle: string): Promise<ResearchSession>;
    updateUserProfile(displayName: string, institution: string | null, researchField: string | null): Promise<UserProfile>;
}
import type { LiteratureReview as _LiteratureReview, ObjectiveId as _ObjectiveId, Paper as _Paper, PaperId as _PaperId, ResearchSession as _ResearchSession, SearchResponse as _SearchResponse, SessionId as _SessionId, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPaper(arg0: PaperId, arg1: string, arg2: Array<string>, arg3: string, arg4: string, arg5: string): Promise<Paper> {
        if (this.processError) {
            try {
                const result = await this.actor.addPaper(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Paper_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPaper(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Paper_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createObjective(arg0: ObjectiveId, arg1: SessionId, arg2: string, arg3: bigint): Promise<Objective> {
        if (this.processError) {
            try {
                const result = await this.actor.createObjective(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createObjective(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createSession(arg0: SessionId, arg1: string, arg2: string, arg3: string | null): Promise<ResearchSession> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0, arg1, arg2, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3));
                return from_candid_ResearchSession_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0, arg1, arg2, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3));
            return from_candid_ResearchSession_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUserProfile(arg0: string, arg1: string | null, arg2: string | null): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
                return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
            return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteLiteratureReview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLiteratureReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLiteratureReview(arg0);
            return result;
        }
    }
    async deleteObjective(arg0: ObjectiveId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteObjective(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteObjective(arg0);
            return result;
        }
    }
    async deletePaper(arg0: PaperId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePaper(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePaper(arg0);
            return result;
        }
    }
    async deleteSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSession(arg0);
            return result;
        }
    }
    async getAllSessions(): Promise<Array<ResearchSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessions();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessions();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLiteratureReview(arg0: string): Promise<LiteratureReview | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiteratureReview(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiteratureReview(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getObjective(arg0: ObjectiveId): Promise<Objective> {
        if (this.processError) {
            try {
                const result = await this.actor.getObjective(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObjective(arg0);
            return result;
        }
    }
    async getObjectivesBySession(arg0: SessionId): Promise<Array<Objective>> {
        if (this.processError) {
            try {
                const result = await this.actor.getObjectivesBySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObjectivesBySession(arg0);
            return result;
        }
    }
    async getPaper(arg0: PaperId): Promise<Paper> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaper(arg0);
                return from_candid_Paper_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaper(arg0);
            return from_candid_Paper_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPapersByObjective(arg0: ObjectiveId): Promise<Array<Paper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPapersByObjective(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPapersByObjective(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPapersBySession(arg0: SessionId): Promise<Array<Paper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPapersBySession(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPapersBySession(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: string): Promise<ResearchSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_ResearchSession_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_ResearchSession_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveLiteratureReview(arg0: string, arg1: string, arg2: Array<string>, arg3: Array<LitReviewReference>): Promise<LiteratureReview> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLiteratureReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLiteratureReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async searchExternalDatabases(arg0: string): Promise<SearchResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.searchExternalDatabases(arg0);
                return from_candid_SearchResponse_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchExternalDatabases(arg0);
            return from_candid_SearchResponse_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchSessionsByTitle(arg0: string): Promise<Array<ResearchSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSessionsByTitle(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSessionsByTitle(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async transformOutcall(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformOutcall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformOutcall(arg0);
            return result;
        }
    }
    async updatePaper(arg0: Paper): Promise<Paper> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaper(to_candid_Paper_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Paper_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaper(to_candid_Paper_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Paper_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSessionTitle(arg0: string, arg1: string): Promise<ResearchSession> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSessionTitle(arg0, arg1);
                return from_candid_ResearchSession_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSessionTitle(arg0, arg1);
            return from_candid_ResearchSession_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: string, arg1: string | null, arg2: string | null): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
                return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
            return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Paper_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Paper): Paper {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ResearchSession_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResearchSession): ResearchSession {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_SearchResponse_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchResponse): SearchResponse {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LiteratureReview]): LiteratureReview | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    status: string;
    title: string;
    createdAt: _Time;
    proposalText: string;
    objectives: Array<_ObjectiveId>;
    proposalFileName: [] | [string];
}): {
    id: SessionId;
    status: string;
    title: string;
    createdAt: Time;
    proposalText: string;
    objectives: Array<ObjectiveId>;
    proposalFileName?: string;
} {
    return {
        id: value.id,
        status: value.status,
        title: value.title,
        createdAt: value.createdAt,
        proposalText: value.proposalText,
        objectives: value.objectives,
        proposalFileName: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.proposalFileName))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    displayName: string;
    institution: [] | [string];
    createdAt: _Time;
    researchField: [] | [string];
}): {
    principal: Principal;
    displayName: string;
    institution?: string;
    createdAt: Time;
    researchField?: string;
} {
    return {
        principal: value.principal,
        displayName: value.displayName,
        institution: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.institution)),
        createdAt: value.createdAt,
        researchField: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.researchField))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arxivResults: Array<_Paper>;
    semanticScholarResults: Array<_Paper>;
}): {
    arxivResults: Array<Paper>;
    semanticScholarResults: Array<Paper>;
} {
    return {
        arxivResults: from_candid_vec_n24(_uploadFile, _downloadFile, value.arxivResults),
        semanticScholarResults: from_candid_vec_n24(_uploadFile, _downloadFile, value.semanticScholarResults)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaperId;
    abstractText: string;
    title: string;
    references: Array<string>;
    fetchedContent: [] | [string];
    sourceUrl: string;
    relevanceScore: [] | [number];
    sourceType: string;
    keywords: Array<string>;
    summary: [] | [string];
    addedAt: _Time;
    authors: Array<string>;
    fullTextAvailable: boolean;
    citationAPA: [] | [string];
    citationMLA: [] | [string];
}): {
    id: PaperId;
    abstractText: string;
    title: string;
    references: Array<string>;
    fetchedContent?: string;
    sourceUrl: string;
    relevanceScore?: number;
    sourceType: string;
    keywords: Array<string>;
    summary?: string;
    addedAt: Time;
    authors: Array<string>;
    fullTextAvailable: boolean;
    citationAPA?: string;
    citationMLA?: string;
} {
    return {
        id: value.id,
        abstractText: value.abstractText,
        title: value.title,
        references: value.references,
        fetchedContent: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.fetchedContent)),
        sourceUrl: value.sourceUrl,
        relevanceScore: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.relevanceScore)),
        sourceType: value.sourceType,
        keywords: value.keywords,
        summary: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.summary)),
        addedAt: value.addedAt,
        authors: value.authors,
        fullTextAvailable: value.fullTextAvailable,
        citationAPA: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.citationAPA)),
        citationMLA: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.citationMLA))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResearchSession>): Array<ResearchSession> {
    return value.map((x)=>from_candid_ResearchSession_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Paper>): Array<Paper> {
    return value.map((x)=>from_candid_Paper_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Paper_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Paper): _Paper {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    displayName: string;
    institution?: string;
    createdAt: Time;
    researchField?: string;
}): {
    principal: Principal;
    displayName: string;
    institution: [] | [string];
    createdAt: _Time;
    researchField: [] | [string];
} {
    return {
        principal: value.principal,
        displayName: value.displayName,
        institution: value.institution ? candid_some(value.institution) : candid_none(),
        createdAt: value.createdAt,
        researchField: value.researchField ? candid_some(value.researchField) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: PaperId;
    abstractText: string;
    title: string;
    references: Array<string>;
    fetchedContent?: string;
    sourceUrl: string;
    relevanceScore?: number;
    sourceType: string;
    keywords: Array<string>;
    summary?: string;
    addedAt: Time;
    authors: Array<string>;
    fullTextAvailable: boolean;
    citationAPA?: string;
    citationMLA?: string;
}): {
    id: _PaperId;
    abstractText: string;
    title: string;
    references: Array<string>;
    fetchedContent: [] | [string];
    sourceUrl: string;
    relevanceScore: [] | [number];
    sourceType: string;
    keywords: Array<string>;
    summary: [] | [string];
    addedAt: _Time;
    authors: Array<string>;
    fullTextAvailable: boolean;
    citationAPA: [] | [string];
    citationMLA: [] | [string];
} {
    return {
        id: value.id,
        abstractText: value.abstractText,
        title: value.title,
        references: value.references,
        fetchedContent: value.fetchedContent ? candid_some(value.fetchedContent) : candid_none(),
        sourceUrl: value.sourceUrl,
        relevanceScore: value.relevanceScore ? candid_some(value.relevanceScore) : candid_none(),
        sourceType: value.sourceType,
        keywords: value.keywords,
        summary: value.summary ? candid_some(value.summary) : candid_none(),
        addedAt: value.addedAt,
        authors: value.authors,
        fullTextAvailable: value.fullTextAvailable,
        citationAPA: value.citationAPA ? candid_some(value.citationAPA) : candid_none(),
        citationMLA: value.citationMLA ? candid_some(value.citationMLA) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
